
#this is the bad practice to create the application.yml file and chnage role again and again
#insted of this use the intellijidea to set the role of profile click on "v" buuton near to run ->select edit config->inside Environment variable write spring.profiles.active =dev

#insted of intellij on production run jar using command line (.\mvnw clean package -D spring.profiles.active=dev)
#if there are tests in project folder only use .\mvnw clean package
#then use -> ls
#         ->cd .\target\
#         ->ls
#         ->java -jar jar_name --spring.profiles.active=dev
#
#

spring:
  profiles:
    active: dev;


#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp: ERROR


#for overall project
#logging:
#  level:
#    root: ERROR